import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('主进程安装全局异常兜底并复用统一退出清理', async () => {
  const source = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  assert.match(source, /process\.on\('uncaughtException'/)
  assert.match(source, /process\.on\('unhandledRejection'/)
  assert.match(source, /async function shutdownDesktop/)
  assert.equal((source.match(/quitDesktopApp\(/g) ?? []).length, 1)
})

test('缺少离线 store 时仍执行官方清理和补种入口', async () => {
  const source = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  assert.doesNotMatch(source, /if \(pluginStoreDir !== undefined\) \{\s*try \{\s*const seeded = await seedBundledPlugins/)
})

test('主窗口导航完成前不结束启动或插件热重载', async () => {
  const source = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  // 恢复页使用专用导航：DSH 页面确认可用后才切换内容视图。
  assert.equal((source.match(/await openWorkbenchOrRecovery\(/g) ?? []).length, 2)
  assert.match(source, /isRecycling = true\s+broadcastShellState\(\)\s+try \{\s+await showStartupWindow\(desktopText\('加载中', 'Loading'\)\)/)
  assert.match(source, /console\.error\('显示启动错误页面失败。'/)
  assert.match(source, /will-navigate'[\s\S]*?windowNavigation\.isNavigating\(\)[\s\S]*?event\.preventDefault\(\)/)
  assert.match(source, /watchProfileActivation\(profileDir, scheduleProfileActivationRecycle/)
  assert.match(source, /waitForDshMarketBatchToSettle\(/)
  assert.match(source, /function handleDshIpc\(message: unknown\): void \{[\s\S]*?scheduleProfileActivationRecycle\(\)/)
  assert.match(source, /profileActivationRecycleGeneration !== generation\) continue/)
  assert.match(source, /escapeRoute\(/)
  assert.doesNotMatch(source, /contents === dshView\?\.webContents \|\| contents === mainWindow\?\.webContents/)
  assert.match(source, /dshSettingsDialogVisible/)
  assert.match(source, /\[role=\"dialog\"\]\[aria-modal=\"true\"\]/)
  assert.match(source, /\^\(设置\|settings\)\$/)
  assert.match(source, /dismissDshSettingsDialog\(\)/)
  assert.match(source, /DSH_MARKET_BATCH_MAX_WAIT_MS/)
})

test('桌面壳与 DSH 内容分层并复用托盘重载实现', async () => {
  const source = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  assert.match(source, /new WebContentsView/)
  assert.match(source, /window\.contentView\.addChildView\(view\)/)
  assert.match(source, /id === 'reload'\) await recycleDshForPluginUpdate\(\)/)
  assert.match(source, /if \(id === 'reload'\) \{\s+await recycleDshForPluginUpdate\(\)/)
  assert.match(source, /title: DESKTOP_APP_NAME/)
})

test('插件恢复页使用独立内容视图和受限 preload，不复用 DSH 侧栏', async () => {
  const main = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  const recovery = await readFile(new URL('../../assets/recovery.html', import.meta.url), 'utf8')
  assert.match(main, /let recoveryView: WebContentsView \| undefined/)
  assert.match(main, /preload: resolvePreload\('recovery-preload\.cjs'\)/)
  assert.match(main, /function showRecoveryWindow/)
  assert.match(main, /window\.unmaximize\(\)\s+window\.setSize\(920, 680\)/)
  assert.match(main, /dshView\?\.setVisible\(false\)/)
  assert.match(recovery, /恢复模式/)
  assert.doesNotMatch(recovery, /dshShell/)
  assert.doesNotMatch(recovery, /class="titlebar"/)
  assert.doesNotMatch(recovery, /class="steps"/)
  assert.match(recovery, /进入工作台/)
  assert.match(recovery, /检测到可能导致启动失败的插件/)
  assert.match(recovery, /显示完整启动日志/)
  assert.match(recovery, /正在重新启动 DSH，最长等待 45 秒。/)
  assert.match(recovery, /--danger-fill/)
})

test('恢复页返回工作台会先确认 DSH 页面可用再切换视图', async () => {
  const main = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  assert.match(main, /async function returnToWorkbenchFromRecovery\(\): Promise<void>/)
  assert.match(main, /running: server !== undefined/)
  assert.match(main, /await windowNavigation\.navigate\(view, \(\) => view\.webContents\.loadURL\(running\.url\)\)/)
  assert.match(main, /advanceDshStartupDiagnostic\(profileDir, 'renderer-loading'\)/)
  assert.match(main, /startRendererHealthTimer\(profileDir\)/)
  assert.match(main, /showDshContentView\(\)\s+mainWindow\?\.maximize\(\)\s+mainWindow\?\.show\(\)\s+mainWindow\?\.focus\(\)\s+if \(profileDir !== undefined\) await maybeLeaveRecoveryMode\(profileDir\)/)
})

test('恢复最近正常配置成功后退出恢复状态并直接进入工作台', async () => {
  const main = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  assert.match(main, /restoreProfileHealthCheckpoint\(profileDir\)\s+await leaveRecoveryMode\(profileDir\)\s+clearRecoverySessionHints\(\)\s+await restartDshInRecoveryMode\(profileDir, 'workbench'\)/)
  assert.match(main, /if \(destination === 'workbench'\) \{\s+await returnToWorkbenchFromRecovery\(\)\s+\} else \{\s+await showRecoveryWindow\(profileDir\)\s+\}/)
})

test('没有隔离插件时启动会自动退出恢复模式并进入工作台', async () => {
  const main = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  assert.match(main, /async function openWorkbenchOrRecovery\(profileDir: string, serverUrl: string\): Promise<void>/)
  assert.match(main, /if \(isRecoveryModeActive\(profileDir\)\) \{\s+if \(await maybeLeaveRecoveryMode\(profileDir\)\) \{\s+await createMainWindow\(serverUrl\)\s+return\s+\}\s+await showRecoveryWindow\(profileDir\)/)
  assert.match(main, /await openWorkbenchOrRecovery\(profileDir, server\.url\)/)
  assert.match(main, /await openWorkbenchOrRecovery\(seedOptions\.profileDir, server\.url\)/)
})

test('恢复模式中的健康启动不会覆盖最近正常配置检查点', async () => {
  const main = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  const healthyBranch = main.match(/if \(report\.status === 'healthy'\) \{([\s\S]*?)\n  \}/)?.[1]
  assert.ok(healthyBranch)
  assert.match(healthyBranch, /await completeStartupDiagnostic/)
  assert.match(healthyBranch, /await maybeLeaveRecoveryMode\(profileDir\)/)
  assert.match(healthyBranch, /if \(!isRecoveryModeActive\(profileDir\)\) \{\s+await captureProfileHealthCheckpoint\(profileDir\)/)
  assert.match(main, /beginStartupDiagnostic\(startupDiagnosticPath\(profileDir\), startupDiagnosticStage, \{\s+mode: isRecoveryModeActive\(profileDir\) \? 'recovery' : 'normal',?\s+\}\)/)
})

test('恢复页只有在 DSH 服务就绪后才显示进入工作台操作', async () => {
  const main = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  const recovery = await readFile(new URL('../../assets/recovery.html', import.meta.url), 'utf8')
  assert.match(recovery, /state\.active && state\.running/)
  assert.match(recovery, /const hasFailure = typeof state\.failureMessage === 'string'/)
  assert.match(recovery, /showLog\.hidden = !hasFailure/)
  assert.match(main, /await reportStartupFailure\(error, profileDir\)/)
  assert.match(main, /join\(profileDir, '\.dsh-desktop-startup-error\.log'\)/)
})

test('恢复页使用单页诊断布局并跟随系统颜色模式', async () => {
  const recovery = await readFile(new URL('../../assets/recovery.html', import.meta.url), 'utf8')
  assert.match(recovery, /当前配置：web/)
  assert.match(recovery, /启动错误/)
  assert.match(recovery, /恢复操作/)
  assert.match(recovery, /matchMedia\('\(prefers-color-scheme: dark\)'\)/)
  assert.match(recovery, /\.dialog-actions button\{min-height:32px;padding:0 10px;font-size:13px\}/)
  assert.match(recovery, /\.dialog-actions \.primary\{min-width:0\}/)
  assert.doesNotMatch(recovery, /class="steps"/)
})

test('桌面壳预加载脚本被编译并提供 DSH 动作兜底', async () => {
  const config = await readFile(new URL('../../tsconfig.json', import.meta.url), 'utf8')
  const preload = await readFile(new URL('../../src/dsh-view-preload.cts', import.meta.url), 'utf8')
  assert.match(config, /src\/\*\*\/\*\.cts/)
  assert.match(preload, /clientBridgeRegistrations/)
  assert.match(preload, /runDomAction/)
  assert.match(preload, /添加工作区\|打开文件夹/)
  assert.match(preload, /\.dcu-wb-session\[role="treeitem"\]\[aria-selected\]/)
  assert.match(preload, /\^新建任务\$/)
})

test('桌面菜单使用窗口内坐标且 DSH 客户端桥接导出标准插件入口', async () => {
  const main = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  const bridge = await readFile(new URL('../../src/desktop-bridge-client-source.ts', import.meta.url), 'utf8')
  const dshPreload = await readFile(new URL('../../src/dsh-view-preload.cts', import.meta.url), 'utf8')
  assert.match(main, /x: Math\.round\(request\.x\),\s+y: Math\.round\(request\.y\)/)
  assert.doesNotMatch(main, /contentBounds\.x \+ Math\.round\(request\.x\)/)
  assert.match(bridge, /window\.__ModuleLoader__\.load/)
  assert.match(bridge, /const inject/)
  assert.match(bridge, /const apply/)
  assert.match(bridge, /ctx\.workspaces\.startSession\(\)/)
})

test('关于窗口使用独立丰富页面并进入打包资源', async () => {
  const main = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  const manifest = await readFile(new URL('../../package.json', import.meta.url), 'utf8')
  const about = await readFile(new URL('../../assets/about.html', import.meta.url), 'utf8')
  assert.match(main, /showAboutWindow\(\)/)
  assert.match(manifest, /assets\/about\.html/)
  assert.match(about, /关于这个项目/)
  assert.match(about, /runtimeVersion/)
  assert.match(about, /overflow:hidden/)
  assert.match(main, /resizable: false/)
  assert.match(main, /frame: false/)
  assert.match(main, /minimizable: false/)
  assert.match(main, /maximizable: false/)
  assert.match(main, /function preventWindowsOwnedWindowFlash/)
  assert.match(main, /window\.setParentWindow\(null\)/)
})

test('桌面通知和更新设置使用独立窗口并进入打包资源', async () => {
  const main = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  const manifest = await readFile(new URL('../../package.json', import.meta.url), 'utf8')
  const settings = await readFile(new URL('../../assets/settings.html', import.meta.url), 'utf8')
  assert.match(main, /showDesktopSettingsWindow\(\)/)
  assert.match(main, /new Notification\(/)
  assert.match(main, /ensureWindowsNotificationIdentity\(\)/)
  assert.match(main, /setToastActivatorCLSID/)
  assert.match(main, /toastActivatorClsid:/)
  assert.match(main, /hasReply: true/)
  assert.match(main, /buildWindowsReplyToastXml/)
  assert.match(main, /Notification\.handleActivation/)
  assert.match(main, /parseWindowsNotificationReplyActivation/)
  assert.match(main, /replyArguments: windowsNotificationReplyArguments\(event\.sessionId\)/)
  assert.match(main, /replyLabel: zh \? '回复' : 'Reply'/)
  assert.match(main, /`\$\{status\} · \$\{event\.title\}`/)
  assert.match(main, /supportsReply && process\.platform !== 'win32'/)
  assert.match(main, /writeShortcutLink\(/)
  assert.match(main, /setOverlayIcon\(/)
  assert.match(manifest, /assets\/settings\.html/)
  assert.match(manifest, /assets\/task-badges/)
  assert.match(settings, /任务完成通知/)
  assert.match(settings, /approvalsEnabled/)
  assert.match(settings, /questionsEnabled/)
  assert.match(settings, /role="listbox"/)
  assert.match(settings, /class="select-menu"/)
  assert.doesNotMatch(settings, /<select/)
  assert.match(main, /mayReportDshLocale/)
  assert.match(main, /broadcastShellBootstrap/)
  assert.match(settings, /api\.onBootstrap/)
  assert.match(settings, /id="updatesNav"/)
  assert.match(settings, /id="updatesPage"/)
  assert.match(settings, /data-value="notify"/)
  assert.match(settings, /data-value="auto-download"/)
  assert.match(settings, /data-value="manual"/)
  assert.match(settings, /api\.updateUpdatePreferences/)
  assert.match(settings, /api\.desktopUpdateAction/)
  assert.match(settings, /api\.closeDesktopSettings/)
  assert.match(main, /SHELL_IPC\.closeDesktopSettings/)
  assert.match(settings, /api\.onDesktopUpdateState/)
  assert.match(settings, /安装前始终由你确认/)
  assert.match(settings, /Installation always requires your confirmation/)
  assert.match(main, /showDesktopSettingsWindow\('updates'\)/)
  assert.match(main, /autoInstallOnAppQuit = false/)
  assert.match(main, /function removeNativeWindowMenu/)
  assert.match(main, /window\.setMenu\(null\)/)
  assert.match(main, /window\.setMenuBarVisibility\(false\)/)
  assert.equal((main.match(/removeNativeWindowMenu\(window\)/g) ?? []).length, 3)
})

test('shell 在 macOS 为交通灯预留空间且状态早到不会读取空 bootstrap', async () => {
  const shell = await readFile(new URL('../../assets/shell.html', import.meta.url), 'utf8')
  assert.match(shell, /data-platform="darwin"[^}]*padding-left:78px/)
  assert.ok(shell.indexOf('document.documentElement.dataset.platform=window.dshShell.platform') < shell.indexOf('<style>'))
  assert.match(shell, /bootstrap\?\.locale/)
  assert.match(shell, /state\?\?value\.state/)
})

test('原生菜单关闭后才清理外壳菜单的选中状态', async () => {
  const main = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  const shell = await readFile(new URL('../../assets/shell.html', import.meta.url), 'utf8')
  assert.match(main, /function popupShellMenu\(request: ShellMenuPopupRequest\): Promise<void>/)
  assert.match(main, /menu\.once\('menu-will-close', close\)/)
  assert.match(main, /callback: close/)
  assert.match(shell, /function clearOpenMenu\(button=openMenu\)/)
  assert.match(shell, /try\{await api\.popupMenu\([\s\S]*?\)\}finally\{clearOpenMenu\(button\)\}/)
  assert.match(shell, /document\.addEventListener\('pointerdown',[\s\S]*?clearOpenMenu\(\)/)
  assert.doesNotMatch(shell, /:root\[data-color-scheme="light"\] \.menu:hover,:root\[data-color-scheme="light"\] \.menu\[aria-expanded="true"\]\{background/)
})

test('DSH 主题变化同步到桌面外壳、原生菜单和辅助窗口', async () => {
  const main = await readFile(new URL('../../src/main.ts', import.meta.url), 'utf8')
  const bridge = await readFile(new URL('../../src/desktop-bridge-client-source.ts', import.meta.url), 'utf8')
  const dshPreload = await readFile(new URL('../../src/dsh-view-preload.cts', import.meta.url), 'utf8')
  const shell = await readFile(new URL('../../assets/shell.html', import.meta.url), 'utf8')
  const settings = await readFile(new URL('../../assets/settings.html', import.meta.url), 'utf8')
  const shortcuts = await readFile(new URL('../../assets/shortcuts.html', import.meta.url), 'utf8')
  const about = await readFile(new URL('../../assets/about.html', import.meta.url), 'utf8')
  const startup = await readFile(new URL('../../assets/startup.html', import.meta.url), 'utf8')
  assert.doesNotMatch(bridge, /inject = \[[^\]]*'theme'/)
  assert.match(dshPreload, /reportDocumentTheme/)
  assert.match(dshPreload, /attributeFilter: \['style'\]/)
  assert.match(main, /nativeTheme\.themeSource = preference/)
  assert.match(main, /setTitleBarOverlay/)
  assert.match(shell, /linear-gradient\(90deg,#1f2121 0%,#1e2120 16%,#1c2221 29%,#1b2223 48%,#1b2222 61%,#1e2120 79%,#1f2020 100%\)/)
  assert.match(shell, /linear-gradient\(105deg,#eff5f3/)
  for (const source of [shell, settings, shortcuts, about, startup]) {
    assert.match(source, /data-color-scheme="light"/)
  }
  for (const source of [shell, settings, shortcuts, about]) assert.match(source, /dataset\.colorScheme=value\.colorScheme/)
  assert.match(main, /loadFile\(html, \{ query: \{ theme: activeDshColorScheme \} \}\)/)
})
