const { contextBridge, ipcRenderer } = require('electron') as typeof import('electron')

const RECOVERY_IPC = {
  activate: 'dsh-recovery:activate',
  getStatus: 'dsh-recovery:get-status',
  keepIsolated: 'dsh-recovery:keep-isolated',
  getStartupLog: 'dsh-recovery:get-startup-log',
  restore: 'dsh-recovery:restore',
  restoreHealthyConfig: 'dsh-recovery:restore-healthy-config',
  returnToWorkbench: 'dsh-recovery:return-to-workbench',
  uninstall: 'dsh-recovery:uninstall',
  // Checkpoints and profiles — capabilities that already existed in the backend but
  // had no way to reach the recovery page.
  listCheckpoints: 'dsh-recovery:list-checkpoints',
  inspectCheckpoint: 'dsh-recovery:inspect-checkpoint',
  restoreCheckpoint: 'dsh-recovery:restore-checkpoint',
  listProfiles: 'dsh-recovery:list-profiles',
  dataDirectory: 'dsh-recovery:data-directory',
  selectDataDirectory: 'dsh-recovery:select-data-directory',
  factoryReset: 'dsh-recovery:factory-reset',
  openTarget: 'dsh-recovery:open-target',
  restart: 'dsh-recovery:restart',
  enterSafeMode: 'dsh-recovery:enter-safe-mode',
  exportDiagnostics: 'dsh-recovery:export-diagnostics',
  showDiagnostics: 'dsh-recovery:show-diagnostics',
  switchProfile: 'dsh-recovery:switch-profile',
  createProfile: 'dsh-recovery:create-profile',
} as const

contextBridge.exposeInMainWorld('dshRecovery', {
  activate: () => ipcRenderer.invoke(RECOVERY_IPC.activate),
  getStatus: () => ipcRenderer.invoke(RECOVERY_IPC.getStatus),
  keepIsolated: (packageName: string) => ipcRenderer.invoke(RECOVERY_IPC.keepIsolated, packageName),
  getStartupLog: () => ipcRenderer.invoke(RECOVERY_IPC.getStartupLog),
  restore: (packageName: string) => ipcRenderer.invoke(RECOVERY_IPC.restore, packageName),
  restoreHealthyConfig: () => ipcRenderer.invoke(RECOVERY_IPC.restoreHealthyConfig),
  returnToWorkbench: () => ipcRenderer.invoke(RECOVERY_IPC.returnToWorkbench),
  uninstall: (packageName: string) => ipcRenderer.invoke(RECOVERY_IPC.uninstall, packageName),
  listCheckpoints: () => ipcRenderer.invoke(RECOVERY_IPC.listCheckpoints),
  inspectCheckpoint: (slotId: string) => ipcRenderer.invoke(RECOVERY_IPC.inspectCheckpoint, slotId),
  restoreCheckpoint: (slotId: string) => ipcRenderer.invoke(RECOVERY_IPC.restoreCheckpoint, slotId),
  listProfiles: () => ipcRenderer.invoke(RECOVERY_IPC.listProfiles),
  dataDirectory: () => ipcRenderer.invoke(RECOVERY_IPC.dataDirectory),
  selectDataDirectory: (target: string | null) => ipcRenderer.invoke(RECOVERY_IPC.selectDataDirectory, target),
  factoryReset: () => ipcRenderer.invoke(RECOVERY_IPC.factoryReset),
  openTarget: (target: string) => ipcRenderer.invoke(RECOVERY_IPC.openTarget, target),
  restart: () => ipcRenderer.invoke(RECOVERY_IPC.restart),
  enterSafeMode: () => ipcRenderer.invoke(RECOVERY_IPC.enterSafeMode),
  exportDiagnostics: () => ipcRenderer.invoke(RECOVERY_IPC.exportDiagnostics),
  showDiagnostics: () => ipcRenderer.invoke(RECOVERY_IPC.showDiagnostics),
  switchProfile: (name: string) => ipcRenderer.invoke(RECOVERY_IPC.switchProfile, name),
  createProfile: (name: string) => ipcRenderer.invoke(RECOVERY_IPC.createProfile, name),
})
